sudo: true

language: node_js
node_js: "12.10.0"

before_install:
  - #cd XonakiBrowser

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Deploy Mac
      os: osx
      osx_image: xcode11.2
      script:
        - npm run deploy:mac
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy Windows      
      os: windows      
      script:                
        - npm run deploy:win    
    - stage: Deploy Linux      
      os: linux   
      dist: bionic   
      script:                
        - npm run deploy:linux    