sudo: false

language: node_js
node_js: "12.10.0"

before_install:
  - #cd XonakiBrowser
  - ls

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Deploy Windows, Linux & Mac
      os: osx
      osx_image: xcode10.1
      script:
        - npm run deploy:all
        - npm run deploy:linux
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine